# H2 in-memory database
spring.datasource.url=jdbc:h2:mem:librarydb
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

# JPA / Hibernate settings
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect

# AUTO = Hibernate creates/updates tables from your @Entity classes automatically
spring.jpa.hibernate.ddl-auto=update

# Shows the SQL Hibernate generates
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# H2 browser console  http://localhost:8080/h2-console
spring.h2.console.enabled=true

spring.application.name=book-library